### ISSUE TITLE
Issue with building the project

### ISSUE THREAD

**Issue by angjunkang** [JuUnland/Chess#5]
A little late to this project but came across this while I was looking for some ideas for my CPP project. I encountered an issue similar to a past issue as seen below. Could you advise me on how to navigate this?

![image](https://github.com/user-attachments/assets/6383f970-3281-4d31-9def-89a1802ca3ad)

**Comment by JuUnland** [comment]
Hey, 

its been years since i built this. No clue tbh but it looks like the textures are not placed in the right directory. You could try to check the whether the relative paths are correct or not.

Greets, Julian

Am Sonntag, Juli 21, 2024 14:47 CEST, schrieb Jun Kang ***@***.***>:
 
 
A little late to this project but came across this while I was looking for some ideas for my CPP project. I encountered an issue similar to a past issue as seen below. Could you advise me on how to navigate this?
image.png (view on web)

**Comment by angjunkang** [comment]
Hey. I managed to got it fixed (not really fixed but I looked through your header files and classes and used them as an idea/guideline to create my own)! Thanks for the reply and I appreciate your time. Good work on the project as well! I'm sure it helped many along the way.
